# Generated by Django 3.0.4 on 2020-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
    ]
