# Generated by Django 3.0.4 on 2020-03-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20200309_2112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmarkedanswer',
            table='question_bookmarked_answer',
        ),
        migrations.AlterModelTable(
            name='bookmarkedquestion',
            table='question_bookmarked_question',
        ),
    ]
