# Generated by Django 3.0.4 on 2020-03-09 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0008_auto_20200309_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkedanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmarkedquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
